#!/usr/bin/env sh
set -e

url="https://raw.githubusercontent.com/webuni/shell-task-runner/master/runner"
[ -f ./.runner ] || wget -q "$url" -O- > .runner || curl -fso .runner "$url"
. ./.runner

_decorator()( _decorator_docker_compose_run "$@" )

# Install all dependencies
task_deps()( task_composer install 2>&1 )

# Run composer
# @service php
task_composer()( composer "$@" )

# Run tests
# @service php-tools
task_tests()( phpunit --colors=always "$@" )

# Fix code style
# @service php-tools
task_cs()( php-cs-fixer fix --ansi --allow-risky=yes "$@" )

# Analyse code
# @service php-tools
task_analyse()( phpstan analyse -l 7 -c phpstan.neon --no-progress --ansi src "$@" )

# Remove all containers in project (use -v to remove volumes also)
task_clean()( _docker_compose down --remove-orphans  "$@" )
